<?php
global $config, $bd;

$resultado = $bd->Execute("SHOW TABLES LIKE 'ssti_gestao'");
$existe = ($resultado->RecordCount() ? TRUE : FALSE);
if(!$existe) {
	$bd->Execute("CREATE TABLE ssti_gestao (
	ssti_gestao_id INTEGER(100) UNSIGNED NOT NULL AUTO_INCREMENT,
	ssti_gestao_ssti INTEGER(100) UNSIGNED DEFAULT NULL,
	ssti_gestao_semelhante INTEGER(100) UNSIGNED DEFAULT NULL,
	ssti_gestao_projeto INTEGER(100) UNSIGNED DEFAULT NULL,
	ssti_gestao_tarefa INTEGER(100) UNSIGNED DEFAULT NULL,
	ssti_gestao_perspectiva INTEGER(100) UNSIGNED DEFAULT NULL,
	ssti_gestao_tema INTEGER(100) UNSIGNED DEFAULT NULL,
	ssti_gestao_objetivo INTEGER(100) UNSIGNED DEFAULT NULL,
	ssti_gestao_fator INTEGER(100) UNSIGNED DEFAULT NULL,
	ssti_gestao_estrategia INTEGER(100) UNSIGNED DEFAULT NULL,
	ssti_gestao_meta INTEGER(100) UNSIGNED DEFAULT NULL,
	ssti_gestao_pratica INTEGER(100) UNSIGNED DEFAULT NULL,
	ssti_gestao_indicador INTEGER(100) UNSIGNED DEFAULT NULL,
	ssti_gestao_acao INTEGER(100) UNSIGNED DEFAULT NULL,
	ssti_gestao_canvas INTEGER(100) UNSIGNED DEFAULT NULL,
	ssti_gestao_risco INTEGER(100) UNSIGNED DEFAULT NULL,
	ssti_gestao_risco_resposta INTEGER(100) UNSIGNED DEFAULT NULL,
	ssti_gestao_calendario INTEGER(100) UNSIGNED DEFAULT NULL,
	ssti_gestao_monitoramento INTEGER(100) UNSIGNED DEFAULT NULL,
	ssti_gestao_ata INTEGER(100) UNSIGNED DEFAULT NULL,
	ssti_gestao_mswot INTEGER(100) UNSIGNED DEFAULT NULL,
	ssti_gestao_swot INTEGER(100) UNSIGNED DEFAULT NULL,
	ssti_gestao_operativo INTEGER(100) UNSIGNED DEFAULT NULL,
	ssti_gestao_instrumento INTEGER(100) UNSIGNED DEFAULT NULL,
	ssti_gestao_recurso INTEGER(100) UNSIGNED DEFAULT NULL,
	ssti_gestao_problema INTEGER(100) UNSIGNED DEFAULT NULL,
	ssti_gestao_demanda INTEGER(100) UNSIGNED DEFAULT NULL,
	ssti_gestao_programa INTEGER(100) UNSIGNED DEFAULT NULL,
	ssti_gestao_licao INTEGER(100) UNSIGNED DEFAULT NULL,
	ssti_gestao_evento INTEGER(100) UNSIGNED DEFAULT NULL,
	ssti_gestao_link INTEGER(100) UNSIGNED DEFAULT NULL,
	ssti_gestao_avaliacao INTEGER(100) UNSIGNED DEFAULT NULL,
	ssti_gestao_tgn INTEGER(100) UNSIGNED DEFAULT NULL,
	ssti_gestao_brainstorm INTEGER(100) UNSIGNED DEFAULT NULL,
	ssti_gestao_gut INTEGER(100) UNSIGNED DEFAULT NULL,
	ssti_gestao_causa_efeito INTEGER(100) UNSIGNED DEFAULT NULL,
	ssti_gestao_arquivo INTEGER(100) UNSIGNED DEFAULT NULL,
	ssti_gestao_forum INTEGER(100) UNSIGNED DEFAULT NULL,
	ssti_gestao_checklist INTEGER(100) UNSIGNED DEFAULT NULL,
	ssti_gestao_agenda INTEGER(100) UNSIGNED DEFAULT NULL,
	ssti_gestao_agrupamento INTEGER(100) UNSIGNED DEFAULT NULL,
	ssti_gestao_patrocinador INTEGER(100) UNSIGNED DEFAULT NULL,
	ssti_gestao_template INTEGER(100) UNSIGNED DEFAULT NULL,
	ssti_gestao_painel INTEGER(100) UNSIGNED DEFAULT NULL,
	ssti_gestao_painel_odometro INTEGER(100) UNSIGNED DEFAULT NULL,
	ssti_gestao_painel_composicao INTEGER(100) UNSIGNED DEFAULT NULL,
	ssti_gestao_tr INTEGER(100) UNSIGNED DEFAULT NULL,
	ssti_gestao_me INTEGER(100) UNSIGNED DEFAULT NULL,
	ssti_gestao_acao_item INTEGER(100) UNSIGNED DEFAULT NULL,
	ssti_gestao_beneficio INTEGER(100) UNSIGNED DEFAULT NULL,
	ssti_gestao_painel_slideshow INTEGER(100) UNSIGNED DEFAULT NULL,
	ssti_gestao_projeto_viabilidade INTEGER(100) UNSIGNED DEFAULT NULL,
	ssti_gestao_projeto_abertura INTEGER(100) UNSIGNED DEFAULT NULL,
	ssti_gestao_plano_gestao INTEGER(100) UNSIGNED DEFAULT NULL,
	ssti_gestao_laudo INTEGER(100) UNSIGNED DEFAULT NULL,
	ssti_gestao_trelo INTEGER(100) UNSIGNED DEFAULT NULL,
	ssti_gestao_trelo_cartao INTEGER(100) UNSIGNED DEFAULT NULL,
	ssti_gestao_pdcl INTEGER(100) UNSIGNED DEFAULT NULL,
	ssti_gestao_pdcl_item INTEGER(100) UNSIGNED DEFAULT NULL,
	ssti_gestao_ordem INTEGER(100) UNSIGNED DEFAULT NULL,
	ssti_gestao_uuid VARCHAR(36) DEFAULT NULL,
	PRIMARY KEY ssti_gestao_id (ssti_gestao_id),
	KEY ssti_gestao_ssti (ssti_gestao_ssti),
	KEY ssti_gestao_semelhante (ssti_gestao_semelhante),
	KEY ssti_gestao_projeto (ssti_gestao_projeto),
	KEY ssti_gestao_tarefa (ssti_gestao_tarefa),
	KEY ssti_gestao_perspectiva (ssti_gestao_perspectiva),
	KEY ssti_gestao_tema (ssti_gestao_tema),
	KEY ssti_gestao_objetivo (ssti_gestao_objetivo),
	KEY ssti_gestao_estrategia (ssti_gestao_estrategia),
	KEY ssti_gestao_meta (ssti_gestao_meta),
	KEY ssti_gestao_fator (ssti_gestao_fator),
	KEY ssti_gestao_pratica (ssti_gestao_pratica),
	KEY ssti_gestao_indicador (ssti_gestao_indicador),
	KEY ssti_gestao_acao (ssti_gestao_acao),
	KEY ssti_gestao_canvas (ssti_gestao_canvas),
	KEY ssti_gestao_risco (ssti_gestao_risco),
	KEY ssti_gestao_risco_resposta (ssti_gestao_risco_resposta),
	KEY ssti_gestao_calendario (ssti_gestao_calendario),
	KEY ssti_gestao_monitoramento (ssti_gestao_monitoramento),
	KEY ssti_gestao_ata (ssti_gestao_ata),
	KEY ssti_gestao_mswot(ssti_gestao_mswot),
	KEY ssti_gestao_swot(ssti_gestao_swot),
	KEY ssti_gestao_operativo(ssti_gestao_operativo),
	KEY ssti_gestao_instrumento (ssti_gestao_instrumento),
	KEY ssti_gestao_recurso (ssti_gestao_recurso),
	KEY ssti_gestao_problema (ssti_gestao_problema),
	KEY ssti_gestao_demanda (ssti_gestao_demanda),
	KEY ssti_gestao_programa (ssti_gestao_programa),
	KEY ssti_gestao_licao (ssti_gestao_licao),
	KEY ssti_gestao_evento (ssti_gestao_evento),
	KEY ssti_gestao_link (ssti_gestao_link),
	KEY ssti_gestao_avaliacao (ssti_gestao_avaliacao),
	KEY ssti_gestao_tgn (ssti_gestao_tgn),
	KEY ssti_gestao_brainstorm (ssti_gestao_brainstorm),
	KEY ssti_gestao_gut (ssti_gestao_gut),
	KEY ssti_gestao_causa_efeito (ssti_gestao_causa_efeito),
	KEY ssti_gestao_arquivo (ssti_gestao_arquivo),
	KEY ssti_gestao_forum (ssti_gestao_forum),
	KEY ssti_gestao_checklist (ssti_gestao_checklist),
	KEY ssti_gestao_agenda (ssti_gestao_agenda),
	KEY ssti_gestao_agrupamento (ssti_gestao_agrupamento),
	KEY ssti_gestao_patrocinador (ssti_gestao_patrocinador),
	KEY ssti_gestao_template (ssti_gestao_template),
	KEY ssti_gestao_painel (ssti_gestao_painel),
	KEY ssti_gestao_painel_odometro (ssti_gestao_painel_odometro),
	KEY ssti_gestao_painel_composicao (ssti_gestao_painel_composicao),
	KEY ssti_gestao_tr (ssti_gestao_tr),
	KEY ssti_gestao_me (ssti_gestao_me),
	KEY ssti_gestao_acao_item (ssti_gestao_acao_item),
	KEY ssti_gestao_beneficio (ssti_gestao_beneficio),
	KEY ssti_gestao_painel_slideshow (ssti_gestao_painel_slideshow),
	KEY ssti_gestao_projeto_viabilidade (ssti_gestao_projeto_viabilidade),
	KEY ssti_gestao_projeto_abertura (ssti_gestao_projeto_abertura),
	KEY ssti_gestao_plano_gestao (ssti_gestao_plano_gestao),
	KEY ssti_gestao_laudo (ssti_gestao_laudo),
	KEY ssti_gestao_trelo (ssti_gestao_trelo),
	KEY ssti_gestao_trelo_cartao (ssti_gestao_trelo_cartao),
	KEY ssti_gestao_pdcl (ssti_gestao_pdcl),
	KEY ssti_gestao_pdcl_item (ssti_gestao_pdcl_item),
	CONSTRAINT ssti_gestao_ssti FOREIGN KEY (ssti_gestao_ssti) REFERENCES ssti (ssti_id) ON DELETE CASCADE ON UPDATE CASCADE,
	CONSTRAINT ssti_gestao_semelhante FOREIGN KEY (ssti_gestao_semelhante) REFERENCES ssti (ssti_id) ON DELETE SET NULL ON UPDATE CASCADE,
	CONSTRAINT ssti_gestao_projeto FOREIGN KEY (ssti_gestao_projeto) REFERENCES projetos (projeto_id) ON DELETE CASCADE ON UPDATE CASCADE,
	CONSTRAINT ssti_gestao_tarefa FOREIGN KEY (ssti_gestao_tarefa) REFERENCES tarefas (tarefa_id) ON DELETE CASCADE ON UPDATE CASCADE,
	CONSTRAINT ssti_gestao_perspectiva FOREIGN KEY (ssti_gestao_perspectiva) REFERENCES perspectivas (pg_perspectiva_id) ON DELETE CASCADE ON UPDATE CASCADE,
	CONSTRAINT ssti_gestao_tema FOREIGN KEY (ssti_gestao_tema) REFERENCES tema (tema_id) ON DELETE CASCADE ON UPDATE CASCADE,
	CONSTRAINT ssti_gestao_objetivo FOREIGN KEY (ssti_gestao_objetivo) REFERENCES objetivo (objetivo_id) ON DELETE CASCADE ON UPDATE CASCADE,
	CONSTRAINT ssti_gestao_fator FOREIGN KEY (ssti_gestao_fator) REFERENCES fator (fator_id) ON DELETE CASCADE ON UPDATE CASCADE,
	CONSTRAINT ssti_gestao_estrategia FOREIGN KEY (ssti_gestao_estrategia) REFERENCES estrategias (pg_estrategia_id) ON DELETE CASCADE ON UPDATE CASCADE,
	CONSTRAINT ssti_gestao_meta FOREIGN KEY (ssti_gestao_meta) REFERENCES metas (pg_meta_id) ON DELETE CASCADE ON UPDATE CASCADE,
	CONSTRAINT ssti_gestao_pratica FOREIGN KEY (ssti_gestao_pratica) REFERENCES praticas (pratica_id) ON DELETE CASCADE ON UPDATE CASCADE,
	CONSTRAINT ssti_gestao_indicador FOREIGN KEY (ssti_gestao_indicador) REFERENCES pratica_indicador (pratica_indicador_id) ON DELETE CASCADE ON UPDATE CASCADE,
	CONSTRAINT ssti_gestao_acao FOREIGN KEY (ssti_gestao_acao) REFERENCES plano_acao (plano_acao_id) ON DELETE CASCADE ON UPDATE CASCADE,
	CONSTRAINT ssti_gestao_canvas FOREIGN KEY (ssti_gestao_canvas) REFERENCES canvas (canvas_id) ON DELETE CASCADE ON UPDATE CASCADE,
	CONSTRAINT ssti_gestao_risco FOREIGN KEY (ssti_gestao_risco) REFERENCES risco (risco_id) ON DELETE CASCADE ON UPDATE CASCADE,
	CONSTRAINT ssti_gestao_risco_resposta FOREIGN KEY (ssti_gestao_risco_resposta) REFERENCES risco_resposta (risco_resposta_id) ON DELETE CASCADE ON UPDATE CASCADE,
	CONSTRAINT ssti_gestao_calendario FOREIGN KEY (ssti_gestao_calendario) REFERENCES calendario (calendario_id) ON DELETE CASCADE ON UPDATE CASCADE,
	CONSTRAINT ssti_gestao_monitoramento FOREIGN KEY (ssti_gestao_monitoramento) REFERENCES monitoramento (monitoramento_id) ON DELETE CASCADE ON UPDATE CASCADE,
	CONSTRAINT ssti_gestao_ata FOREIGN KEY (ssti_gestao_ata) REFERENCES ata (ata_id) ON DELETE CASCADE ON UPDATE CASCADE,
	CONSTRAINT ssti_gestao_mswot FOREIGN KEY (ssti_gestao_mswot) REFERENCES mswot (mswot_id) ON DELETE CASCADE ON UPDATE CASCADE,
	CONSTRAINT ssti_gestao_swot FOREIGN KEY (ssti_gestao_swot) REFERENCES swot (swot_id) ON DELETE CASCADE ON UPDATE CASCADE,
	CONSTRAINT ssti_gestao_operativo FOREIGN KEY (ssti_gestao_operativo) REFERENCES operativo (operativo_id) ON DELETE CASCADE ON UPDATE CASCADE,
	CONSTRAINT ssti_gestao_instrumento FOREIGN KEY (ssti_gestao_instrumento) REFERENCES instrumento (instrumento_id) ON DELETE CASCADE ON UPDATE CASCADE,
	CONSTRAINT ssti_gestao_recurso FOREIGN KEY (ssti_gestao_recurso) REFERENCES recursos (recurso_id) ON DELETE CASCADE ON UPDATE CASCADE,
	CONSTRAINT ssti_gestao_problema FOREIGN KEY (ssti_gestao_problema) REFERENCES problema (problema_id) ON DELETE CASCADE ON UPDATE CASCADE,
	CONSTRAINT ssti_gestao_demanda FOREIGN KEY (ssti_gestao_demanda) REFERENCES demandas (demanda_id) ON DELETE CASCADE ON UPDATE CASCADE,
	CONSTRAINT ssti_gestao_programa FOREIGN KEY (ssti_gestao_programa) REFERENCES programa (programa_id) ON DELETE CASCADE ON UPDATE CASCADE,
	CONSTRAINT ssti_gestao_licao FOREIGN KEY (ssti_gestao_licao) REFERENCES licao (licao_id) ON DELETE CASCADE ON UPDATE CASCADE,
	CONSTRAINT ssti_gestao_evento FOREIGN KEY (ssti_gestao_evento) REFERENCES eventos (evento_id) ON DELETE CASCADE ON UPDATE CASCADE,
	CONSTRAINT ssti_gestao_link FOREIGN KEY (ssti_gestao_link) REFERENCES links (link_id) ON DELETE CASCADE ON UPDATE CASCADE,
	CONSTRAINT ssti_gestao_avaliacao FOREIGN KEY (ssti_gestao_avaliacao) REFERENCES avaliacao (avaliacao_id) ON DELETE CASCADE ON UPDATE CASCADE,
	CONSTRAINT ssti_gestao_tgn FOREIGN KEY (ssti_gestao_tgn) REFERENCES tgn (tgn_id) ON DELETE CASCADE ON UPDATE CASCADE,
	CONSTRAINT ssti_gestao_brainstorm FOREIGN KEY (ssti_gestao_brainstorm) REFERENCES brainstorm (brainstorm_id) ON DELETE CASCADE ON UPDATE CASCADE,
	CONSTRAINT ssti_gestao_gut FOREIGN KEY (ssti_gestao_gut) REFERENCES gut (gut_id) ON DELETE CASCADE ON UPDATE CASCADE,
	CONSTRAINT ssti_gestao_causa_efeito FOREIGN KEY (ssti_gestao_causa_efeito) REFERENCES causa_efeito (causa_efeito_id) ON DELETE CASCADE ON UPDATE CASCADE,
	CONSTRAINT ssti_gestao_arquivo FOREIGN KEY (ssti_gestao_arquivo) REFERENCES arquivo (arquivo_id) ON DELETE CASCADE ON UPDATE CASCADE,
	CONSTRAINT ssti_gestao_forum FOREIGN KEY (ssti_gestao_forum) REFERENCES foruns (forum_id) ON DELETE CASCADE ON UPDATE CASCADE,
	CONSTRAINT ssti_gestao_checklist FOREIGN KEY (ssti_gestao_checklist) REFERENCES checklist (checklist_id) ON DELETE CASCADE ON UPDATE CASCADE,
	CONSTRAINT ssti_gestao_agenda FOREIGN KEY (ssti_gestao_agenda) REFERENCES agenda (agenda_id) ON DELETE CASCADE ON UPDATE CASCADE,
	CONSTRAINT ssti_gestao_agrupamento FOREIGN KEY (ssti_gestao_agrupamento) REFERENCES agrupamento (agrupamento_id) ON DELETE CASCADE ON UPDATE CASCADE,
	CONSTRAINT ssti_gestao_patrocinador FOREIGN KEY (ssti_gestao_patrocinador) REFERENCES patrocinadores (patrocinador_id) ON DELETE CASCADE ON UPDATE CASCADE,
	CONSTRAINT ssti_gestao_template FOREIGN KEY (ssti_gestao_template) REFERENCES template (template_id) ON DELETE CASCADE ON UPDATE CASCADE,
	CONSTRAINT ssti_gestao_painel FOREIGN KEY (ssti_gestao_painel) REFERENCES painel (painel_id) ON DELETE CASCADE ON UPDATE CASCADE,
	CONSTRAINT ssti_gestao_painel_odometro FOREIGN KEY (ssti_gestao_painel_odometro) REFERENCES painel_odometro (painel_odometro_id) ON DELETE CASCADE ON UPDATE CASCADE,
	CONSTRAINT ssti_gestao_painel_composicao FOREIGN KEY (ssti_gestao_painel_composicao) REFERENCES painel_composicao (painel_composicao_id) ON DELETE CASCADE ON UPDATE CASCADE,
	CONSTRAINT ssti_gestao_tr FOREIGN KEY (ssti_gestao_tr) REFERENCES tr (tr_id) ON DELETE CASCADE ON UPDATE CASCADE,
	CONSTRAINT ssti_gestao_me FOREIGN KEY (ssti_gestao_me) REFERENCES me (me_id) ON DELETE CASCADE ON UPDATE CASCADE,
	CONSTRAINT ssti_gestao_acao_item FOREIGN KEY (ssti_gestao_acao_item) REFERENCES plano_acao_item (plano_acao_item_id) ON DELETE CASCADE ON UPDATE CASCADE,
	CONSTRAINT ssti_gestao_beneficio FOREIGN KEY (ssti_gestao_beneficio) REFERENCES beneficio (beneficio_id) ON DELETE CASCADE ON UPDATE CASCADE,
	CONSTRAINT ssti_gestao_painel_slideshow FOREIGN KEY (ssti_gestao_painel_slideshow) REFERENCES painel_slideshow (painel_slideshow_id) ON DELETE CASCADE ON UPDATE CASCADE,
	CONSTRAINT ssti_gestao_projeto_viabilidade FOREIGN KEY (ssti_gestao_projeto_viabilidade) REFERENCES projeto_viabilidade (projeto_viabilidade_id) ON DELETE CASCADE ON UPDATE CASCADE,
	CONSTRAINT ssti_gestao_projeto_abertura FOREIGN KEY (ssti_gestao_projeto_abertura) REFERENCES projeto_abertura (projeto_abertura_id) ON DELETE CASCADE ON UPDATE CASCADE,
	CONSTRAINT ssti_gestao_plano_gestao FOREIGN KEY (ssti_gestao_plano_gestao) REFERENCES plano_gestao (pg_id) ON DELETE CASCADE ON UPDATE CASCADE,
	CONSTRAINT ssti_gestao_laudo FOREIGN KEY (ssti_gestao_laudo) REFERENCES laudo (laudo_id) ON DELETE CASCADE ON UPDATE CASCADE,
	CONSTRAINT ssti_gestao_trelo FOREIGN KEY (ssti_gestao_trelo) REFERENCES trelo (trelo_id) ON DELETE CASCADE ON UPDATE CASCADE,
	CONSTRAINT ssti_gestao_trelo_cartao FOREIGN KEY (ssti_gestao_trelo_cartao) REFERENCES trelo_cartao (trelo_cartao_id) ON DELETE CASCADE ON UPDATE CASCADE,
	CONSTRAINT ssti_gestao_pdcl FOREIGN KEY (ssti_gestao_pdcl) REFERENCES pdcl (pdcl_id) ON DELETE CASCADE ON UPDATE CASCADE,
	CONSTRAINT ssti_gestao_pdcl_item FOREIGN KEY (ssti_gestao_pdcl_item) REFERENCES pdcl_item (pdcl_item_id) ON DELETE CASCADE ON UPDATE CASCADE
)ENGINE=InnoDB CHARACTER SET latin1 COLLATE latin1_swedish_ci;");
	}

?>