SET FOREIGN_KEY_CHECKS=0;

UPDATE versao SET versao_codigo='8.5.01';
UPDATE versao SET ultima_atualizacao_bd='2017-02-23';
UPDATE versao SET ultima_atualizacao_codigo='2017-02-23';
UPDATE versao SET versao_bd=393;

INSERT INTO campo_formulario (campo_formulario_tipo, campo_formulario_campo, campo_formulario_descricao, campo_formulario_ativo) VALUES
	('perspectivas','pg_perspectiva_cia','Organização responsável',1),
	('perspectivas','pg_perspectiva_cias','Organizações envolvidas',0),
	('perspectivas','pg_perspectiva_dept','Seção responsável',1),
	('perspectivas','pg_perspectiva_depts','Seções envolvidas',0),
	('perspectivas','pg_perspectiva_usuario','Responsável',1),
	('perspectivas','pg_perspectiva_designados','Designados',0),
	('perspectivas','pg_perspectiva_aprovado','Aprovado',1),
	('perspectivas','pg_perspectiva_percentagem','Percentagem',1),
	('perspectivas','pg_perspectiva_cor','Cor',1),
	('perspectivas','pg_perspectiva_descricao','Descrição',0),
	('perspectivas','pg_perspectiva_oque','O Que Fazer',0),
	('perspectivas','pg_perspectiva_onde','Onde Fazer',0),
	('perspectivas','pg_perspectiva_quando','Quando Fazer',0),
	('perspectivas','pg_perspectiva_como','Como Fazer',0),
	('perspectivas','pg_perspectiva_porque','Por Que Fazer',0),
	('perspectivas','pg_perspectiva_quanto','Quanto Custa',0),
	('perspectivas','pg_perspectiva_quem','Quem Faz',0),
	('perspectivas','pg_perspectiva_controle','Método de Controle',0),
	('perspectivas','pg_perspectiva_melhorias','Melhorias Efetuadas',0),
	('perspectivas','pg_perspectiva_metodo_aprendizado','Método de Aprendizado',0),
	('perspectivas','pg_perspectiva_desde_quando','Desde Quando',0),
	('perspectivas','pg_perspectiva_tipo_pontuacao','Sistema de Percentagem',0),
	('temas','tema_cia','Organização responsável',1),
	('temas','tema_cias','Organizações envolvidas',0),
	('temas','tema_dept','Seção responsável',1),
	('temas','tema_depts','Seções envolvidas',0),
	('temas','tema_usuario','Responsável',1),
	('temas','tema_designados','Designados',0),
	('temas','tema_aprovado','Aprovado',1),
	('temas','tema_percentagem','Percentagem',1),
	('temas','tema_cor','Cor',1),
	('temas','tema_relacionado','Relacionado',1),
	('temas','tema_descricao','Descrição',0),
	('temas','tema_oque','O Que Fazer',0),
	('temas','tema_onde','Onde Fazer',0),
	('temas','tema_quando','Quando Fazer',0),
	('temas','tema_como','Como Fazer',0),
	('temas','tema_porque','Por Que Fazer',0),
	('temas','tema_quanto','Quanto Custa',0),
	('temas','tema_quem','Quem Faz',0),
	('temas','tema_controle','Método de Controle',0),
	('temas','tema_melhorias','Melhorias Efetuadas',0),
	('temas','tema_metodo_aprendizado','Método de Aprendizado',0),
	('temas','tema_desde_quando','Desde Quando',0),
	('temas','tema_tipo_pontuacao','Sistema de Percentagem',0),
	('objetivos','objetivo_cia','Organização responsável',1),
	('objetivos','objetivo_cias','Organizações envolvidas',0),
	('objetivos','objetivo_dept','Seção responsável',1),
	('objetivos','objetivo_depts','Seções envolvidas',0),
	('objetivos','objetivo_usuario','Responsável',1),
	('objetivos','objetivo_designados','Designados',0),
	('objetivos','objetivo_aprovado','Aprovado',1),
	('objetivos','objetivo_percentagem','Percentagem',1),
	('objetivos','objetivo_cor','Cor',1),
	('objetivos','objetivo_relacionado','Relacionado',1),
	('objetivos','objetivo_descricao','Descrição',0),
	('objetivos','objetivo_oque','O Que Fazer',0),
	('objetivos','objetivo_onde','Onde Fazer',0),
	('objetivos','objetivo_quando','Quando Fazer',0),
	('objetivos','objetivo_como','Como Fazer',0),
	('objetivos','objetivo_porque','Por Que Fazer',0),
	('objetivos','objetivo_quanto','Quanto Custa',0),
	('objetivos','objetivo_quem','Quem Faz',0),
	('objetivos','objetivo_controle','Método de Controle',0),
	('objetivos','objetivo_melhorias','Melhorias Efetuadas',0),
	('objetivos','objetivo_metodo_aprendizado','Método de Aprendizado',0),
	('objetivos','objetivo_desde_quando','Desde Quando',0),
	('objetivos','objetivo_tipo_pontuacao','Sistema de Percentagem',0),
	('mes','me_cia','Organização responsável',1),
	('mes','me_cias','Organizações envolvidas',0),
	('mes','me_dept','Seção responsável',1),
	('mes','me_depts','Seções envolvidas',0),
	('mes','me_usuario','Responsável',1),
	('mes','me_designados','Designados',0),
	('mes','me_aprovado','Aprovado',1),
	('mes','me_percentagem','Percentagem',1),
	('mes','me_cor','Cor',1),
	('mes','me_relacionado','Relacionado',1),
	('mes','me_descricao','Descrição',0),
	('mes','me_oque','O Que Fazer',0),
	('mes','me_onde','Onde Fazer',0),
	('mes','me_quando','Quando Fazer',0),
	('mes','me_como','Como Fazer',0),
	('mes','me_porque','Por Que Fazer',0),
	('mes','me_quanto','Quanto Custa',0),
	('mes','me_quem','Quem Faz',0),
	('mes','me_controle','Método de Controle',0),
	('mes','me_melhorias','Melhorias Efetuadas',0),
	('mes','me_metodo_aprendizado','Método de Aprendizado',0),
	('mes','me_desde_quando','Desde Quando',0),
	('mes','me_tipo_pontuacao','Sistema de Percentagem',0),
	('fatores','fator_cia','Organização responsável',1),
	('fatores','fator_cias','Organizações envolvidas',0),
	('fatores','fator_dept','Seção responsável',1),
	('fatores','fator_depts','Seções envolvidas',0),
	('fatores','fator_usuario','Responsável',1),
	('fatores','fator_designados','Designados',0),
	('fatores','fator_aprovado','Aprovado',1),
	('fatores','fator_percentagem','Percentagem',1),
	('fatores','fator_cor','Cor',1),
	('fatores','fator_relacionado','Relacionado',1),
	('fatores','fator_descricao','Descrição',0),
	('fatores','fator_oque','O Que Fazer',0),
	('fatores','fator_onde','Onde Fazer',0),
	('fatores','fator_quando','Quando Fazer',0),
	('fatores','fator_como','Como Fazer',0),
	('fatores','fator_porque','Por Que Fazer',0),
	('fatores','fator_quanto','Quanto Custa',0),
	('fatores','fator_quem','Quem Faz',0),
	('fatores','fator_controle','Método de Controle',0),
	('fatores','fator_melhorias','Melhorias Efetuadas',0),
	('fatores','fator_metodo_aprendizado','Método de Aprendizado',0),
	('fatores','fator_desde_quando','Desde Quando',0),
	('fatores','fator_tipo_pontuacao','Sistema de Percentagem',0),
	('estrategias','pg_estrategia_cia','Organização responsável',1),
	('estrategias','pg_estrategia_cias','Organizações envolvidas',0),
	('estrategias','pg_estrategia_dept','Seção responsável',1),
	('estrategias','pg_estrategia_depts','Seções envolvidas',0),
	('estrategias','pg_estrategia_usuario','Responsável',1),
	('estrategias','pg_estrategia_designados','Designados',0),
	('estrategias','pg_estrategia_aprovado','Aprovado',1),
	('estrategias','pg_estrategia_percentagem','Percentagem',1),
	('estrategias','pg_estrategia_cor','Cor',1),
	('estrategias','pg_estrategia_relacionado','Relacionado',1),
	('estrategias','pg_estrategia_descricao','Descrição',0),
	('estrategias','pg_estrategia_oque','O Que Fazer',0),
	('estrategias','pg_estrategia_onde','Onde Fazer',0),
	('estrategias','pg_estrategia_quando','Quando Fazer',0),
	('estrategias','pg_estrategia_como','Como Fazer',0),
	('estrategias','pg_estrategia_porque','Por Que Fazer',0),
	('estrategias','pg_estrategia_quanto','Quanto Custa',0),
	('estrategias','pg_estrategia_quem','Quem Faz',0),
	('estrategias','pg_estrategia_controle','Método de Controle',0),
	('estrategias','pg_estrategia_melhorias','Melhorias Efetuadas',0),
	('estrategias','pg_estrategia_metodo_aprendizado','Método de Aprendizado',0),
	('estrategias','pg_estrategia_desde_quando','Desde Quando',0),
	('estrategias','pg_estrategia_tipo_pontuacao','Sistema de Percentagem',0),
	('estrategias','pg_estrategia_ano','Ano',0),
	('estrategias','pg_estrategia_codigo','Código',0),
	('estrategias','pg_estrategia_inicio','Início',0),
	('estrategias','pg_estrategia_fim','Término',0),
	('metas','pg_meta_cia','Organização responsável',1),
	('metas','pg_meta_cias','Organizações envolvidas',0),
	('metas','pg_meta_dept','Seção responsável',1),
	('metas','pg_meta_depts','Seções envolvidas',0),
	('metas','pg_meta_responsavel','Responsável',1),
	('metas','pg_meta_designados','Designados',0),
	('metas','pg_meta_aprovado','Aprovado',1),
	('metas','pg_meta_percentagem','Percentagem',1),
	('metas','pg_meta_cor','Cor',1),
	('metas','pg_meta_relacionado','Relacionado',1),
	('metas','pg_meta_descricao','Descrição',0),
	('metas','pg_meta_oque','O Que Fazer',0),
	('metas','pg_meta_onde','Onde Fazer',0),
	('metas','pg_meta_quando','Quando Fazer',0),
	('metas','pg_meta_como','Como Fazer',0),
	('metas','pg_meta_porque','Por Que Fazer',0),
	('metas','pg_meta_quanto','Quanto Custa',0),
	('metas','pg_meta_quem','Quem Faz',0),
	('metas','pg_meta_controle','Método de Controle',0),
	('metas','pg_meta_melhorias','Melhorias Efetuadas',0),
	('metas','pg_meta_metodo_aprendizado','Método de Aprendizado',0),
	('metas','pg_meta_desde_quando','Desde Quando',0),
	('metas','pg_meta_tipo_pontuacao','Sistema de Percentagem',0),
	('metas','pg_meta_atual','Meta Atual',0),
	('praticas','pratica_cia','Organização responsável',1),
	('praticas','pratica_cias','Organizações envolvidas',0),
	('praticas','pratica_dept','Seção responsável',1),
	('praticas','pratica_depts','Seções envolvidas',0),
	('praticas','pratica_responsavel','Responsável',1),
	('praticas','pratica_designados','Designados',0),
	('praticas','pratica_aprovado','Aprovado',1),
	('praticas','pratica_cor','Cor',1),
	('praticas','pratica_descricao','Descrição',1),
	('praticas','pratica_oque','O Que Fazer',0),
	('praticas','pratica_onde','Onde Fazer',0),
	('praticas','pratica_quando','Quando Fazer',0),
	('praticas','pratica_como','Como Fazer',0),
	('praticas','pratica_porque','Por Que Fazer',0),
	('praticas','pratica_quanto','Quanto Custa',0),
	('praticas','pratica_quem','Quem Faz',0),
	('praticas','pratica_marcadores','Quantidade de Marcadores',1),
	('praticas','pratica_oim','Oportunidades de Inovação e Melhoria',1);

	
	
	
	
