SET FOREIGN_KEY_CHECKS=0;

UPDATE versao SET versao_codigo='8.5.02';
UPDATE versao SET ultima_atualizacao_bd='2017-03-20';
UPDATE versao SET ultima_atualizacao_codigo='2017-03-20';
UPDATE versao SET versao_bd=396;

INSERT INTO campo_formulario (campo_formulario_tipo, campo_formulario_campo, campo_formulario_descricao, campo_formulario_ativo) VALUES
	('programas','programa_cor','Cor',1),
	('programas','programa_cia','Organização responsável',0),
	('programas','programa_cias','Organizações envolvidas',0),
	('programas','programa_dept','Seção responsável',1),
	('programas','programa_depts','Seções envolvidas',0),
	('programas','programa_usuario','Responsável',1),	
	('programas','programa_designados','Designados',0),		
	('programas','programa_aprovado','Aprovado',1),
	('programas','programa_relacionado','Relacionado',1),
	('programas','programa_inicio','Início',1),
	('programas','programa_fim','Término',1),
	('programas','programa_percentagem','Percentagem',1),
	('programas','programa_descricao','Descrição',0),
	('licoes','licao_cor','Cor',1),
	('licoes','licao_cia','Organização responsável',0),
	('licoes','licao_cias','Organizações envolvidas',0),
	('licoes','licao_dept','Seção responsável',1),
	('licoes','licao_depts','Seções envolvidas',0),
	('licoes','licao_responsavel','Responsável',1),	
	('licoes','licao_designados','Designados',0),		
	('licoes','licao_aprovado','Aprovado',1),
	('licoes','licao_relacionado','Relacionado',1),
	('licoes','licao_ocorrencia','Ocorrência',0),
	('licoes','licao_tipo','Tipo',0),
	('licoes','licao_categoria','Categoria',0),
	('licoes','licao_consequencia','Consequências',0),
	('licoes','licao_acao_tomada','Ação tomada',0),
	('licoes','licao_aprendizado','Aprendizado',0),
	('licoes','licao_data_final','Data',0),
	('templates','template_cor','Cor',1),
	('templates','template_cia','Organização responsável',0),
	('templates','template_cias','Organizações envolvidas',0),
	('templates','template_dept','Seção responsável',1),
	('templates','template_depts','Seções envolvidas',0),
	('templates','template_responsavel','Responsável',1),	
	('templates','template_designados','Designados',0),		
	('templates','template_aprovado','Aprovado',1),
	('templates','template_projeto','Projeto',0),
	('templates','template_tipo','Tipo',0),
	('templates','template_gerencial','Gerencial',0),
	('templates','template_descricao','Descrição',1),
	('arquivos','arquivo_cor','Cor',1),
	('arquivos','arquivo_cia','Organização responsável',0),
	('arquivos','arquivo_cias','Organizações envolvidas',0),
	('arquivos','arquivo_dept','Seção responsável',1),
	('arquivos','arquivo_depts','Seções envolvidas',0),
	('arquivos','arquivo_dono','Responsável',1),	
	('arquivos','arquivo_usuario_upload','Responsável pelo Upload',0),	
	('arquivos','arquivo_designados','Designados',0),		
	('arquivos','arquivo_aprovado','Aprovado',1),
	('arquivos','arquivo_relacionado','Relacionado',1),
	('arquivos','arquivo_descricao','Descrição',1),
	('arquivos','arquivo_categoria','Categoria',0),
	('arquivos','arquivo_tipo','Tipo',0),
	('arquivos','arquivo_versao','Versão',1),
	('arquivos','arquivo_pasta','Pasta',1),
	('arquivos','arquivo_tamanho','Tamanho',1),
	('arquivos','arquivo_data','Data de Inclusão',1),
	('arquivo_pastas','arquivo_pasta_cor','Cor',1),
	('arquivo_pastas','arquivo_pasta_cia','Organização responsável',0),
	('arquivo_pastas','arquivo_pasta_cias','Organizações envolvidas',0),
	('arquivo_pastas','arquivo_pasta_dept','Seção responsável',1),
	('arquivo_pastas','arquivo_pasta_depts','Seções envolvidas',0),
	('arquivo_pastas','arquivo_pasta_dono','Responsável',1),	
	('arquivo_pastas','arquivo_pasta_designados','Designados',0),		
	('arquivo_pastas','arquivo_pasta_relacionado','Relacionado',1),
	('arquivo_pastas','arquivo_pasta_descricao','Descrição',1),
	('foruns','forum_cor','Cor',1),
	('foruns','forum_cia','Organização responsável',0),
	('foruns','forum_cias','Organizações envolvidas',0),
	('foruns','forum_dept','Seção responsável',1),
	('foruns','forum_depts','Seções envolvidas',0),
	('foruns','forum_dono','Responsável',1),	
	('foruns','forum_moderador','Moderador',0),	
	('foruns','forum_designados','Designados',0),		
	('foruns','forum_relacionado','Relacionado',1),
	('foruns','forum_aprovado','Aprovado',1),
	('foruns','forum_descricao','Descrição',1),
	('links','link_cor','Cor',1),
	('links','link_cia','Organização responsável',0),
	('links','link_cias','Organizações envolvidas',0),
	('links','link_dept','Seção responsável',1),
	('links','link_depts','Seções envolvidas',0),
	('links','link_dono','Responsável',1),	
	('links','link_designados','Designados',0),		
	('links','link_relacionado','Relacionado',1),
	('links','link_aprovado','Aprovado',1),
	('links','link_descricao','Descrição',1),
	('links','link_categoria','Categoria',1),
	('agrupamentos','agrupamento_cor','Cor',1),
	('agrupamentos','agrupamento_cia','Organização responsável',0),
	('agrupamentos','agrupamento_cias','Organizações envolvidas',0),
	('agrupamentos','agrupamento_dept','Seção responsável',1),
	('agrupamentos','agrupamento_depts','Seções envolvidas',0),
	('agrupamentos','agrupamento_usuario','Responsável',1),	
	('agrupamentos','agrupamento_designados','Designados',0),		
	('agrupamentos','agrupamento_relacionado','Relacionado',1),
	('agrupamentos','agrupamento_aprovado','Aprovado',1),
	('agrupamentos','agrupamento_descricao','Descrição',1),
	('instrumentos','instrumento_cor','Cor',1),
	('instrumentos','instrumento_cia','Organização responsável',0),
	('instrumentos','instrumento_cias','Organizações envolvidas',0),
	('instrumentos','instrumento_dept','Seção responsável',1),
	('instrumentos','instrumento_depts','Seções envolvidas',0),
	('instrumentos','instrumento_responsavel','Responsável',1),	
	('instrumentos','instrumento_designados','Designados',0),		
	('instrumentos','instrumento_relacionado','Relacionado',1),
	('instrumentos','instrumento_aprovado','Aprovado',1),
	('instrumentos','instrumento_supervisor','supervisor',0),	
	('instrumentos','instrumento_autoridade','autoridade',0),	
	('instrumentos','instrumento_cliente','cliente',0),	
	('instrumentos','instrumento_numero','Número',0),	
	('instrumentos','instrumento_ano','Ano',0),	
	('instrumentos','instrumento_licitacao','Licitação',0),	
	('instrumentos','instrumento_edital_nr','Número do Edital',0),	
	('instrumentos','instrumento_processo','Número do Processo',0),	
	('instrumentos','instrumento_objeto','Objeto',0),	
	('instrumentos','instrumento_justificativa','Justificativa',0),	
	('instrumentos','instrumento_entidade','Entidade',0),	
	('instrumentos','instrumento_entidade_cnpj','CNPJ da Entidade',0),	
	('instrumentos','instrumento_data_celebracao','Data de Celebração',0),	
	('instrumentos','instrumento_data_publicacao','Data de Publicação',0),	
	('instrumentos','instrumento_data_inicio','Data de Início',1),	
	('instrumentos','instrumento_data_termino','Data de Término',1),	
	('instrumentos','instrumento_valor','Valor',1),
	('instrumentos','instrumento_valor_atual','Valor Atual',1),
	('instrumentos','instrumento_valor_contrapartida','Contrapartida',0),	
	('instrumentos','instrumento_tipo','Tipo',1),	
	('instrumentos','instrumento_situacao','Situação',1),	
	('instrumentos','instrumento_porcentagem','Percentual Realizado',1),
	('operativos','operativo_cor','Cor',1),
	('operativos','operativo_cia','Organização responsável',0),
	('operativos','operativo_cias','Organizações envolvidas',0),
	('operativos','operativo_dept','Seção responsável',1),
	('operativos','operativo_depts','Seções envolvidas',0),
	('operativos','operativo_usuario','Responsável',1),	
	('operativos','operativo_designados','Designados',0),		
	('operativos','operativo_relacionado','Relacionado',1),
	('operativos','operativo_aprovado','Aprovado',1),
	('operativos','operativo_descricao','Descrição',0),
	('operativos','operativo_previsao','Data',1),
	('operativos','operativo_convenio','Convênio',0),
	('patrocinadores','patrocinador_cor','Cor',1),
	('patrocinadores','patrocinador_cia','Organização responsável',0),
	('patrocinadores','patrocinador_cias','Organizações envolvidas',0),
	('patrocinadores','patrocinador_dept','Seção responsável',1),
	('patrocinadores','patrocinador_depts','Seções envolvidas',0),
	('patrocinadores','patrocinador_responsavel','Responsável',1),	
	('patrocinadores','patrocinador_designados','Designados',0),		
	('patrocinadores','patrocinador_relacionado','Relacionado',1),
	('patrocinadores','patrocinador_aprovado','Aprovado',1),
	('patrocinadores','patrocinador_descricao','Descrição',1),
	('patrocinadores','patrocinador_cidade','Cidade',0),
	('patrocinadores','patrocinador_estado','Estado',0),
	('patrocinadores','patrocinador_pais','País',0),
	('patrocinadores','patrocinador_instrumentos','Instrumentos Jurídicos',0),
	('mswots','mswot_cor','Cor',1),
	('mswots','mswot_cia','Organização responsável',0),
	('mswots','mswot_cias','Organizações envolvidas',0),
	('mswots','mswot_dept','Seção responsável',1),
	('mswots','mswot_depts','Seções envolvidas',0),
	('mswots','mswot_responsavel','Responsável',1),	
	('mswots','mswot_designados','Designados',0),		
	('mswots','mswot_relacionado','Relacionado',1),
	('mswots','mswot_aprovado','Aprovado',1),
	('mswots','mswot_descricao','Descrição',1),
	('mswots','mswot_inicio','Início',1),
	('mswots','mswot_fim','Término',1),
	('mswots','mswot_como','Como',0),
	('mswots','mswot_controle','Controle',0),
	('mswots','mswot_desde_quando','Desde quando',0),
	('mswots','mswot_melhorias','Melhorias',0),
	('mswots','mswot_metodo_aprendizado','Metodo de aprendizado',0),
	('mswots','mswot_onde','Onde',0),
	('mswots','mswot_oque','O que',0),
	('mswots','mswot_porque','Porque',0),
	('mswots','mswot_quando','Quando',0),
	('mswots','mswot_quanto','Quanto',0),
	('mswots','mswot_quem','Quem',0),
	('swots','swot_cor','Cor',1),
	('swots','swot_cia','Organização responsável',0),
	('swots','swot_cias','Organizações envolvidas',0),
	('swots','swot_dept','Seção responsável',1),
	('swots','swot_depts','Seções envolvidas',0),
	('swots','swot_responsavel','Responsável',1),	
	('swots','swot_designados','Designados',0),		
	('swots','swot_relacionado','Relacionado',1),
	('swots','swot_aprovado','Aprovado',1),
	('swots','swot_descricao','Descrição',1),
	('swots','swot_inicio','Início',1),
	('swots','swot_fim','Término',1),
	('swots','swot_g','Gravidade',1),
	('swots','swot_u','Urgência',1),
	('swots','swot_t','Tendência',1),
	('swots','swot_pontuacao','Pontuação GUT',1),
	('swots','swot_como','Como',0),
	('swots','swot_controle','Controle',0),
	('swots','swot_desde_quando','Desde quando',0),
	('swots','swot_melhorias','Melhorias',0),
	('swots','swot_metodo_aprendizado','Metodo de aprendizado',0),
	('swots','swot_onde','Onde',0),
	('swots','swot_oque','O que',0),
	('swots','swot_porque','Porque',0),
	('swots','swot_quando','Quando',0),
	('swots','swot_quanto','Quanto',0),
	('swots','swot_quem','Quem',0);