SET FOREIGN_KEY_CHECKS=0;

UPDATE versao SET versao_codigo='8.5.27';
UPDATE versao SET ultima_atualizacao_bd='2020-07-30';
UPDATE versao SET ultima_atualizacao_codigo='2020-07-30';
UPDATE versao SET versao_bd=578;


INSERT INTO sisvalores (sisvalor_titulo, sisvalor_valor, sisvalor_valor_id, sisvalor_chave_id_pai) VALUES
	('projeto_convenio','SEMA - PROGESTÃO (072/2017/ANA/PROGESTÃO II)','072/2017/ANA/PROGESTÃO II',NULL),
	('projeto_convenio','SEMA - PROGRAMA QUALIAGUA - ANA (001/2017)','001/2017',NULL),
	('projeto_convenio','PROCOMITES (075/2017)','075/2017',NULL),
	('projeto_convenio','SEMA - RESÍDUOS SÓLIDOS - ELABORAÇÃO PLANO ESTADUAL MT (765440/2011)','765440/2011',NULL),
	('projeto_convenio','FUNDO AMAZONIA (13212651)','13212651',NULL),
	('projeto_convenio','PEAAF (801789/2014)','801789/2014',NULL),
	('projeto_regiao','9900 - Mato Grosso','9900',NULL),
	('projeto_regiao','100 - Região I - Noroeste I','100',NULL),
	('projeto_regiao','101 - Região I - Noroeste I - Juína (Cidade Pólo)','101',NULL),
	('projeto_regiao','102 - Região I - Noroeste I - Castanheira','102',NULL),
	('projeto_regiao','103 - Região I - Noroeste I - Juruena','103',NULL),
	('projeto_regiao','104 - Região I - Noroeste I - Cotriguaçu','104',NULL),
	('projeto_regiao','105 - Região I - Noroeste I - Aripuanã','105',NULL),
	('projeto_regiao','106 - Região I - Noroeste I - Colniza','106',NULL),
	('projeto_regiao','107 - Região I - Noroeste I - Rondolândia','107',NULL),
	('projeto_regiao','200 - Região II - Norte','200',NULL),
	('projeto_regiao','201 - Região II - Norte - Alta Floresta (Cidade Pólo)','201',NULL),
	('projeto_regiao','202 - Região II - Norte - Nova Bandeirantes','202',NULL),
	('projeto_regiao','203 - Região II - Norte - Apiacás','203',NULL),
	('projeto_regiao','204 - Região II - Norte - Nova Monte Verde','204',NULL),
	('projeto_regiao','205 - Região II - Norte - Paranaita','205',NULL),
	('projeto_regiao','206 - Região II - Norte - Carlinda','206',NULL),
	('projeto_regiao','207 - Região II - Norte - Nova Canaã do Norte','207',NULL),
	('projeto_regiao','208 - Região II - Norte - Colíder','208',NULL),
	('projeto_regiao','209 - Região II - Norte - Nova Santa Helena','209',NULL),
	('projeto_regiao','210 - Região II - Norte - Terra Nova do Norte','210',NULL),
	('projeto_regiao','211 - Região II - Norte - Novo Mundo','211',NULL),
	('projeto_regiao','212 - Região II - Norte - Guarantã do Norte','212',NULL),
	('projeto_regiao','213 - Região II - Norte - Matupá','213',NULL),
	('projeto_regiao','214 - Região II - Norte - Peixoto de Azevedo','214',NULL),
	('projeto_regiao','215 - Região II - Norte - Nova Guarita','215',NULL),
	('projeto_regiao','300 - Região III - Nordeste','300',NULL),
	('projeto_regiao','301 - Região III - Nordeste - Vila Rica (Cidade Pólo)','301',NULL),
	('projeto_regiao','302 - Região III - Nordeste - Santa Terezinha','302',NULL),
	('projeto_regiao','303 - Região III - Nordeste - Confresa','303',NULL),
	('projeto_regiao','304 - Região III - Nordeste - Porto Alegre do Norte','304',NULL),
	('projeto_regiao','305 - Região III - Nordeste - Santa Cruz do Xingu','305',NULL),
	('projeto_regiao','306 - Região III - Nordeste - São José do Xingu','306',NULL),
	('projeto_regiao','307 - Região III - Nordeste - Cana-Brava do Norte','307',NULL),
	('projeto_regiao','308 - Região III - Nordeste - Alto Boa Vista','308',NULL),
	('projeto_regiao','309 - Região III - Nordeste - São Félix do Araguaia','309',NULL),
	('projeto_regiao','310 - Região III - Nordeste - Serra Nova Dourada','310',NULL),
	('projeto_regiao','311 - Região III - Nordeste - Bom Jesus do Araguaia','311',NULL),
	('projeto_regiao','312 - Região III - Nordeste - Novo Santo Antônio','312',NULL),
	('projeto_regiao','313 - Região III - Nordeste - Luciara','313',NULL),
	('projeto_regiao','400 - Região IV - Leste','400',NULL),
	('projeto_regiao','401 - Região IV - Leste - Barra do Garças (Cidade Pólo)','401',NULL),
	('projeto_regiao','402 - Região IV - Leste - Querência','402',NULL),
	('projeto_regiao','403 - Região IV - Leste - Ribeirão Cascalheira','403',NULL),
	('projeto_regiao','404 - Região IV - Leste - Canarana','404',NULL),
	('projeto_regiao','405 - Região IV - Leste - Nova Nazaré','405',NULL),
	('projeto_regiao','406 - Região IV - Leste - Água Boa','406',NULL),
	('projeto_regiao','407 - Região IV - Leste - Cocalinho','407',NULL),
	('projeto_regiao','408 - Região IV - Leste - Campinápolis','408',NULL),
	('projeto_regiao','409 - Região IV - Leste - Nova Xavantina','409',NULL),
	('projeto_regiao','410 - Região IV - Leste - Novo São Joaquim','410',NULL),
	('projeto_regiao','411 - Região IV - Leste - Araguaiana','411',NULL),
	('projeto_regiao','412 - Região IV - Leste - General Carneiro','412',NULL),
	('projeto_regiao','413 - Região IV - Leste - Pontal do Araguaia','413',NULL),
	('projeto_regiao','414 - Região IV - Leste - Torixoréu','414',NULL),
	('projeto_regiao','415 - Região IV - Leste - Ribeirãozinho','415',NULL),
	('projeto_regiao','416 - Região IV - Leste - Ponta Branca','416',NULL),
	('projeto_regiao','417 - Região IV - Leste - Araguainha','417',NULL),
	('projeto_regiao','500 - Região V - Sudeste','500',NULL),
	('projeto_regiao','501 - Região V - Sudeste - Rondonópolis (Cidade Pólo)','501',NULL),
	('projeto_regiao','502 - Região V - Sudeste - Gaúcha do Norte','502',NULL),
	('projeto_regiao','503 - Região V - Sudeste - Paranatinga','503',NULL),
	('projeto_regiao','504 - Região V - Sudeste - Santo Antônio do Leste','504',NULL),
	('projeto_regiao','505 - Região V - Sudeste - Campo Verde','505',NULL),
	('projeto_regiao','506 - Região V - Sudeste - Primavera do Leste','506',NULL),
	('projeto_regiao','507 - Região V - Sudeste - Dom Aquino','507',NULL),
	('projeto_regiao','508 - Região V - Sudeste - Poxoréu','508',NULL),
	('projeto_regiao','509 - Região V - Sudeste - Tesouro','509',NULL),
	('projeto_regiao','510 - Região V - Sudeste - Jaciara','510',NULL),
	('projeto_regiao','600 - Região VI - Sul','600',NULL),
	('projeto_regiao','601 - Região VI - Sul - Cuiabá (Cidade Pólo)','601',NULL),
	('projeto_regiao','602 - Região VI - Sul - Várzea Grande','602',NULL),
	('projeto_regiao','603 - Região VI - Sul - Nobres','603',NULL),
	('projeto_regiao','604 - Região VI - Sul - Rosário Oeste','604',NULL),
	('projeto_regiao','605 - Região VI - Sul - Acorizal','605',NULL),
	('projeto_regiao','606 - Região VI - Sul - Jangada','606',NULL),
	('projeto_regiao','607 - Região VI - Sul - Planalto da Serra','607',NULL),
	('projeto_regiao','608 - Região VI - Sul - Nova Brasilândia','608',NULL),
	('projeto_regiao','609 - Região VI - Sul - Chapada dos Guimarães','609',NULL),
	('projeto_regiao','610 - Região VI - Sul - Nossa Senhora do Livramento','610',NULL),
	('projeto_regiao','611 - Região VI - Sul - Santo Antônio do Leverger','611',NULL),
	('projeto_regiao','612 - Região VI - Sul - Barão de Melgaço','612',NULL),
	('projeto_regiao','613 - Região VI - Sul - Poconé','613',NULL),
	('projeto_regiao','700 - Região VII - Sudoeste','700',NULL),
	('projeto_regiao','701 - Região VII - Sudoeste - Cáceres (Cidade Pólo)','701',NULL),
	('projeto_regiao','702 - Região VII - Sudoeste - Porto Esperidião','702',NULL),
	('projeto_regiao','703 - Região VII - Sudoeste - Mirassol D’Oeste','703',NULL),
	('projeto_regiao','704 - Região VII - Sudoeste - Glória D’Oeste','704',NULL),
	('projeto_regiao','705 - Região VII - Sudoeste - São José dos Quatro Marcos','705',NULL),
	('projeto_regiao','706 - Região VII - Sudoeste - Curvelândia','706',NULL),
	('projeto_regiao','707 - Região VII - Sudoeste - Araputanga','707',NULL),
	('projeto_regiao','708 - Região VII - Sudoeste - Indiavaí','708',NULL),
	('projeto_regiao','709 - Região VII - Sudoeste - Figueirópolis D’Oeste','709',NULL),
	('projeto_regiao','710 - Região VII - Sudoeste - Lambari D’Oeste','710',NULL),
	('projeto_regiao','711 - Região VII - Sudoeste - Rio Branco','711',NULL),
	('projeto_regiao','712 - Região VII - Sudoeste - Salto do Céu','712',NULL),
	('projeto_regiao','713 - Região VII - Sudoeste - Reserva do Cabaçal','713',NULL),
	('projeto_regiao','714 - Região VII - Sudoeste - Jauru','714',NULL),
	('projeto_regiao','715 - Região VII - Sudoeste - Vale de São Domingos','715',NULL),
	('projeto_regiao','716 - Região VII - Sudoeste - Pontes e Lacerda','716',NULL),
	('projeto_regiao','717 - Região VII - Sudoeste - Vila Bela da Santíssima Trindade','717',NULL),
	('projeto_regiao','718 - Região VII - Sudoeste - Conquista D’Oeste','718',NULL),
	('projeto_regiao','719 - Região VII - Sudoeste - Nova Lacerda','719',NULL),
	('projeto_regiao','720 - Região VII - Sudoeste - Comodoro','720',NULL),
	('projeto_regiao','721 - Região VII - Sudoeste - Campos de Júlio','721',NULL),
	('projeto_regiao','722 - Região VII - Sudoeste - Sapezal','722',NULL),
	('projeto_regiao','800 - Região VIII - Oeste','800',NULL),
	('projeto_regiao','801 - Região VIII - Oeste - Tangará da Serra (Cidade Pólo)','801',NULL),
	('projeto_regiao','802 - Região VIII - Oeste - Porto Estrela','802',NULL),
	('projeto_regiao','803 - Região VIII - Oeste - Barra dos Bugres','803',NULL),
	('projeto_regiao','804 - Região VIII - Oeste - Nova Olímpia','804',NULL),
	('projeto_regiao','805 - Região VIII - Oeste - Denise','805',NULL),
	('projeto_regiao','806 - Região VIII - Oeste - Santo Afonso','806',NULL),
	('projeto_regiao','807 - Região VIII - Oeste - Campo Novo do Parecis','807',NULL),
	('projeto_regiao','808 - Região VIII - Oeste - Brasnorte','808',NULL),
	('projeto_regiao','900 - Região IX - Centro Oeste','900',NULL),
	('projeto_regiao','901 - Região IX - Centro Oeste - Diamantino (Cidade Pólo)','901',NULL),
	('projeto_regiao','902 - Região IX - Centro Oeste - Alto Paraguai','902',NULL),
	('projeto_regiao','903 - Região IX - Centro Oeste - Nortelândia','903',NULL),
	('projeto_regiao','904 - Região IX - Centro Oeste - Arenápolis','904',NULL),
	('projeto_regiao','905 - Região IX - Centro Oeste - Nova Marilândia','905',NULL),
	('projeto_regiao','906 - Região IX - Centro Oeste - São José do Rio Claro','906',NULL),
	('projeto_regiao','907 - Região IX - Centro Oeste - Nova Maringá','907',NULL),
	('projeto_regiao','1000 - Região X - Centro','1000',NULL),
	('projeto_regiao','1001 - Região X - Centro - Sorriso (Cidade Pólo)','1001',NULL),
	('projeto_regiao','1002 - Região X - Centro - Nova Mutum','1002',NULL),
	('projeto_regiao','1003 - Região X - Centro - Santa Rita do Trivelato','1003',NULL),
	('projeto_regiao','1004 - Região X - Centro - Lucas do Rio Verde','1004',NULL),
	('projeto_regiao','1005 - Região X - Centro - Tapurah','1005',NULL),
	('projeto_regiao','1006 - Região X - Centro - Ipiranga do Norte','1006',NULL),
	('projeto_regiao','1007 - Região X - Centro - Itanhangá','1007',NULL),
	('projeto_regiao','1100 - Região XI - Noroeste II','1100',NULL),
	('projeto_regiao','1101 - Região XI - Noroeste II - Juara (Cidade Pólo)','1101',NULL),
	('projeto_regiao','1102 - Região XI - Noroeste II - Porto dos Gaúchos','1102',NULL),
	('projeto_regiao','1103 - Região XI - Noroeste II - Novo Horizonte do Norte','1103',NULL),
	('projeto_regiao','1104 - Região XI - Noroeste II - Tabaporã','1104',NULL),
	('projeto_regiao','1200 - Região XII - Centro Norte','1200',NULL),
	('projeto_regiao','1201 - Região XII - Centro Norte - Sinop ( Cidade Pólo)','1201',NULL),
	('projeto_regiao','1202 - Região XII - Centro Norte - Nova Ubiratã','1202',NULL),
	('projeto_regiao','1203 - Região XII - Centro Norte - Feliz Natal','1203',NULL),
	('projeto_regiao','1204 - Região XII - Centro Norte - Vera','1204',NULL),
	('projeto_regiao','1205 - Região XII - Centro Norte - Santa Carmem','1205',NULL),
	('projeto_regiao','1206 - Região XII - Centro Norte - Cláudia','1206',NULL),
	('projeto_regiao','1207 - Região XII - Centro Norte - União do Sul','1207',NULL),
	('projeto_regiao','1208 - Região XII - Centro Norte - taúba','1208',NULL),
	('projeto_regiao','1209 - Região XII - Centro Norte - Marcelândia','1209',NULL),
	('projeto_fonte','100 - Recursos Ordinários do Tesouro Estadual ','100',NULL),
	('projeto_fonte','193 - Recursos de Transferências Voluntárias','193',NULL),
	('projeto_fonte','195 - Recursos de Transferências da União','195',NULL),
	('projeto_fonte','217 - Recursos Próprios com Finalidades Específicas','217',NULL),
	('projeto_fonte','240 - Recursos Próprios','240',NULL),
	('projeto_fonte','393 - Superavitária de recursos de transferências voluntárias','393',NULL),
	('projeto_fonte','395 - Superavitária de recursos de transferências da União','395',NULL),
	('projeto_fonte','617 - Superavitária de recursos próprios com finalidades especificas','617',NULL),
	('projeto_fonte','640 - Superavitária  de recursos próprios','640',NULL);